  
language: node_js
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy: 
   provider: firebase
   token:
    secure: "Your encrypted token"



on: 
  branch: master